### ISSUE TITLE
Setup instructions - npm install

### ISSUE THREAD

**Issue by NicholasAaronBrady** [smitch88/bmorearoundtown_v2#21]
Hey @clickclickonsal , can see you have 
```
npm install
```
for getting started. I'm just wondering why it isn't 
```
lerna bootstrap
```
a lot of this is pretty new to me.. sorry if its a dumb question 😅

**Comment by clickclickonsal** [comment]
I have a [postinstall script](https://github.com/smitch88/bmorearoundtown_v2/blob/master/package.json#L6) in the root of the package.json. When you run npm install, it then will run `learna bootstrap` in that postinstall script. 😄

**Comment by NicholasAaronBrady** [comment]
ahhhhh haha gotcha! Thanks!
